[package]
name = "reef"
version = "0.2.0"
edition = "2024"
description = "Bash compatibility layer for fish shell"
license = "MIT"

[dependencies]

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
codegen-units = 1
